### ISSUE TITLE
Documentation Shape Complementarity

### ISSUE THREAD

**Issue by jnarvaezp** [maxibor/meetdock#1]
Hi Team

The implementation of shape complementarity is based on the method Lawrence and Colleman ( https://www.ccp4.ac.uk/newsletters/newsletter39/02_sc.html), or which method was implemented? if this method was different, how to get the score?

Thanks

**Comment by maxibor** [comment]
The implementation of shape complementary is based on the method of Chen and Weng, 2002.

The bibliography as well as the description of the meetdock methods are available in this repository.

**Comment by jnarvaezp** [comment]
Thanks @maxibor .
